---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demoapp-gw
spec:
  parentRefs:
  - name: envoyproxy
    namespace: demoapp-gw
  hostnames:
  - "cymbal.sctp-sandbox.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    # filters:
    # - type: URLRewrite
    #   urlRewrite:
    #     path:
    #       type: ReplacePrefixMatch
    #       replacePrefixMatch: /
    backendRefs:
    - name: frontend
      namespace: demoapp
      port: 80